---
test_name:	Create a user

stages:
  - name: create a user
    request:
      url: http://localhost:5000/user
      json:
        user_name:"rohanb12",
        hashed_password:"rohan123",
        full_name:"Rohan Bedarkar",
        email_id:"rohan.bedarkar@gmail.com"
      method: POST
      headers:
        content-type: application/json
    response:
      status_code: 200
      body:
        message:"Data Instersted Sucessfully"
---

test_name: Delete user
stages:
    - name: delete a user
      request:
        url: http://localhost:5000/user
        method: DELETE
        auth:
            - rohanb2
            - rohan123
        headers:
          content-type: application/json
      response:
        status_code: 200
        body:
          message:"Data SucessFully deleted"
