test_name: Delete existing user

stages:
  - name: Make sure you delete existing user
    request:
      url: http://localhost:5001/user
      auth:
        - parag
        - bhingre

      method: DELETE
      headers:
        content-type: application/json
    response:
      status_code: 201
